app:
  name: go-scaffold
  version: 1.0.0

http:
  port: 8080

logger:
  log_level: debug
  rollbar_env: go-scaffold

postgres:
  url: postgres://postgres:postgres@localhost:5432/postgres
  pool_max: 2

#mysql:
#  url: root:root@tcp(localhost:3306)/test?parseTime=true
#  pool_max: 2

#rabbitmq:
#  url: amqp://guest:guest@localhost:5672/
#  rpc_server_exchange: rpc_server
#  rpc_client_exchange: rpc_client
