app:
  name: go-scaffold
  version: 1.0.0

#http:
#  port: 8080

logger:
  dev: true
  level: debug
  paths: [stdout, ./app.log]

jwt:
  private_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRE5Sc012ZnhIenFMZUcKbTBYQVhjMVIzTXowM1VIN2Y1em1Rc3N2NWprTXBYeHl1QUxXTllwRDJqZ1EyamdDbEpVV25SL0FpR0lIQWFyTQp5QVd5QUNRSmFnUkVFY0ljdDB6VlA2N2FGNGR4ZHdVTHA2MzNZelFXL1A4elVYeklZbkYyL0xBWk9YTVRQTlZ1Ck90REpKeDZ5bFBvdEwxZUhMdExscm02QnVhdXY3M2xDRFdBUFc3Q2sxczV2eklEUFIyYkVJWVZQU2wyVjB0NVYKVm8yVXpIdDFGUThNcTJtODdDM2hLMFg5RHpUeWp4aXZFUXZqejJSbm1KTDFCMWFZYzJ1QkNQK1BvMkJXazVzdAptQWhDVkU2S2dOK0t6enc3bnE2SFNBd3pRTU4ycTZ3V0lYOGRFRWt5c04raTNyMURXWVZkbUFIZTh4WHpvWkMyCjBsakFpVHg5QWdNQkFBRUNnZ0VBT2pKWm05bVdxVkduMWsybkZNYURNelk2RlNHMVZ5dnl1NFVzUGNRellGWjYKVmJ1OWNpVnpzWkRvWEQ3QnFsbWRldS9JMUxqVnNjN1RNWU56dWVjNFVFTHlPcW9lTWkzMVptL0xqcUVsRVJJQgpLREM5cldrK2wxWGF0QjNpRnAxeU5aMmwvMEMrVXpIb0FIeEVQUU1PUE9ybmttL2RqTUhGb01BM0xDZ0xlTEVWCjN2SEtrZUN0OGRlNkY3K0tHYW1zbzB2NklhZHZuL2xISTI2SU4rQkowcVJrRERJNkhVb0pxYm5aSnhnVGx1QU8KZHdBWHkzaldpbWV0dUJlT0lUNHdOWFVEaVlkV3FZZFhzNUZSUGU4bWVtbms3bythdERQZkordHdTMlhrU3lEUQp6TFdyK3YxcExqMDhnb2NMVXV0TGZGeFZ3VEt0aFlTbWoyNFk3aHQ2c1FLQmdRRG5IRFE5dUoxbFJBeHNFa0dmCktCdm56MGhiOHhodFhkRjdRV0lYY29JQnVDSEozYzcxOC9TUGhodXcvL1lBNlhsSjNwaVRCQnJxMmdzT0ppRFAKeHZFK2Nla3hFYmQ5dTUzaFZKMmZtck41YnZrVFRPVmh2YVdxNHdOZzExaEZ0dmpjVStPekc1ZWhmZm8rZEh6dQp4L2IwYmtTUGo1Mm5QK1NzZ3lrUFBDRmw3d0tCZ1FEallrL1RwRnBTWmRhQ2p3THlnRU5pSG5NODV4MElhK2pSCm4vbGZFRU1SSmZjWFVpaEJoMU5YVVhwWjh4c21mZndiVXYrRUF6NkJWWlVmWjBVOFBVNGhHcng2cjErUWxjNkcKRG14N1N4YU1WamgveXpkRkZWVXNDdHBhZUJpTjAramc0TDF0M1JQWjNSUDBCUEYxOFlMaVpZdStMZTNraC9LOApXcDM3NmszUVV3S0JnUUNrK2RZMUJSZWVWVkJFeVZkOHhNWCsyVkkvQ1M2enk1Z2hVMUF4aXJWUmd0N2oybW5GCjJ5c0dWV1pwR0o3RWtlWGFISU52MXl0YjRPQ3BiZ0JZTWh5K1JkU0FDYlNobFkramJhTERiMHlVNytudnBDSE8KZnZISEpoeWdRYmtxc3UyOVlra1Y3eWx6eDVrZWdrczRyUmdWN3EwVWlpR3haWVBZdmh4T1dzOUFrd0tCZ1FDbgpMVWp6bWdxdU9pR1VyQURHdW5iUVZRTDA3QmIwY2lJaXZUTmpLVm1sNmZ2Wk1aWlhWMTkyKzNpeFdZUEVzU3dDCkN1dkI2NEN4Sm5NVk82QXp3ZjhIWjlqYmVzVVFVSlFmQzh2R2VsYUJwNEt5c241WVZHN2lpcmd2ZTh6UnVkT20KUXBZRGlGOW45cHNNOWZWeGViZDVMSitwbTZza01xL011L01ibkJESjhRS0JnQnhVWmRXNVF4a2F2M1llbmhQLwpra0w4NlVIRHFsY3hydEJzSkdTZ2k1WW8zdGJpR3BZTzJIQkdGKzZZWklyam9xa2NxVkVVTURzZndQaXZ2aFh6CnlOU1JLOTg2Q1RlZ0RKNE5aWitZSmRqM3l1d1hXL1VrNHRLUFUyQStVSE1ZS3RHVXV3REMrcnE3UWIwcXJqRmMKang0Z1NGY3BGS1ZpZkdDZDdpQXY2LzYrCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6VWJETDM4Ujg2aTNocHRGd0YzTgpVZHpNOU4xQiszK2M1a0xMTCtZNURLVjhjcmdDMWpXS1E5bzRFTm80QXBTVkZwMGZ3SWhpQndHcXpNZ0ZzZ0FrCkNXb0VSQkhDSExkTTFUK3UyaGVIY1hjRkM2ZXQ5Mk0wRnZ6L00xRjh5R0p4ZHZ5d0dUbHpFenpWYmpyUXlTY2UKc3BUNkxTOVhoeTdTNWE1dWdibXJyKzk1UWcxZ0QxdXdwTmJPYjh5QXowZG14Q0dGVDBwZGxkTGVWVmFObE14NwpkUlVQREt0cHZPd3Q0U3RGL1E4MDhvOFlyeEVMNDg5a1o1aVM5UWRXbUhOcmdRai9qNk5nVnBPYkxaZ0lRbFJPCmlvRGZpczg4TzU2dWgwZ01NMEREZHF1c0ZpRi9IUkJKTXJEZm90NjlRMW1GWFpnQjN2TVY4NkdRdHRKWXdJazgKZlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
  access_token_exp: 300
  refresh_token_exp: 2592000

#postgres:
#  url: postgres://postgres:postgres@localhost:5432/postgres
#  pool_max: 2

mysql:
  url: root:root@tcp(localhost:3306)/test?parseTime=true
  pool_max: 2

#rabbitmq:
#  url: amqp://guest:guest@localhost:5672/
#  server_exchange: rpc_server
#  client_exchange: rpc_client

kafka:
  brokers: [kafka1:9092,kafka2:9093,kafka3:9094]

kafka_topics:
  foo_bar_topic:
    name: foo_bar
    partitions: 1
    replicas: 3

redis:
  addrs: [127.0.0.1:6379]
  password: ""
  db: 0
  pool_size: 16