app:
  name: go-scaffold
  version: 1.0.0

http:
  port: 8080

logger:
  level: debug
  development: true
  output_paths: [stdout, ./app.log]

#postgres:
#  url: postgres://postgres:postgres@localhost:5432/postgres
#  pool_max: 2

mysql:
  url: root:root@tcp(localhost:3306)/test?parseTime=true
  pool_max: 2

#rabbitmq:
#  url: amqp://guest:guest@localhost:5672/
#  rpc_server_exchange: rpc_server
#  rpc_client_exchange: rpc_client

kafka:
  brokers: [kafka1:9092,kafka2:9093,kafka3:9094]

kafka_topics:
  foo_bar_topic:
    name: foo_bar
    partitions: 1
    replicas: 3

redis:
  addrs: [127.0.0.1:6379]
  password: ""
  db: 0
  pool_size: 16